name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - 'proto/**'
      - '**.MD'
      - '**.md'
      - '.github/**'
    branches:
      - 'stable'
jobs:
  publish:
    runs-on: ${{matrix.os}}
    
    permissions: write-all
    
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-latest, windows-latest]
    
    steps:
      - name: Check out Git Repo
        uses: actions/checkout@v1
        
      - name: Install Node.js, and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 14
          
      - name: Build/Release Electron App
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/release-') }}
