name: CI
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'proto/**'
    branches:
      - 'releases/**'
jobs:
  linux:
    runs-on: ubuntu-18.04
    name: Linux x64
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: sudo apt update -y && curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt install -y nodejs
    
      - name: Install NodeJS
        run: sudo apt install -y nodejs
        
      - name: Downgrade npm to v6
        run: sudo npm i -g npm@latest-6
        
      - name: Install Packages
        run: npm i --include=dev
        
      - name: Build Application (electron-builder)
        run: npm run build-installer
        
      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: "SixGrid - Linux x64.AppImage"
          path: '${{github.workspace}}/dist/*.AppImage'
  darwin:
    runs-on: macos-10.15
    name: macOS x64
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: brew install node@14
        
      - name: Downgrade npm to v6
        run: npm i -g npm@latest-6
        
      - name: Install Packages
        run: npm i --include=dev
        
      - name: Build Application (electron-builder)
        run: npm run build-installer
        
      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: "SixGrid - macOS x64.dmg"
          path: '${{github.workspace}}/dist/*.dmg'
