name: CI
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Github Release Tag'
        required: true
      name:
        description: 'Github Release Name'
        required: true
  #pull_request:
  #push:
  #  paths-ignore:
  #    - 'proto/**'
  #    - '**.MD'
  #    - '**.md'
  #    - '.github/**'
  #  branches:
  #    - 'stable'
jobs:
  mktag:
    runs-on: ubuntu-latest
    
    permissions: write-all
    
    steps:
      - uses: actions/checkout@master
          
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: ${{ github.event.inputs.name }}
          draft: true
      
  publish:
    needs: mktag
  
    runs-on: ${{matrix.os}}
    
    permissions: write-all
    
    strategy:
      matrix:
        include:
          - os: macos-10.15
            artifact_name: sixgrid.dmg
            asset_name: "sixgrid.${{ github.event.inputs.tag }}.dmg"
          - os: ubuntu-latest
            artifact_name: sixgrid.AppImage
            asset_name: "sixgrid.${{ github.event.inputs.tag }}.AppImage"
          - os: windows-latest
            artifact_name: sixgrid.exe
            asset_name: "sixgrid.${{ github.event.inputs.tag }}.x64_86.exe"
    
    steps:
      - name: Check out Git Repo
        uses: actions/checkout@master
        
      - name: Install Node.js, and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 14
          
      - run: npm i -g npm@latest-6
      - run: npm install --include=dev
      
      - name: Build Electron Application
        run: npm run build-installer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.event.inputs.tag }}
          overwrite: true
